### ISSUE TITLE
Not just SNAPP?

### ISSUE THREAD

**Issue by marty-downs** [NCEAS/scicomp-onboarding#1]
@brunj7 Can I make suggestions in the SciComp onboarding repo that would make it more relevant to LTER? LIke linking to the LTER GitHub organization (https://github.com/lter) and the LTER Slack organization?

**Comment by brunj7** [comment]
Yes, sure! most data interns used to be on SNAPP, so more a legacy than anything else!

**Comment by brunj7** [comment]
updated to LTER with e77f262
